create table serie(
	id serial not null,
	nombre varchar(50) not null,
	anio varchar(10) not null,
	num_temp integer not null,
	descripcion varchar(1000) not null
);

create sequence serie_sequence
	start 1
	increment 1;

alter table serie add constraint PK_serie primary key(id);

insert into Serie values(nextval('serie_sequence'),'DARK','2017',3,'En la ciudad de Winden comienzan a desaparecer niños, sacando a la luz las relaciones fracturadas, vidas dobles y el pasado oscuro de cuatro familias que viven allí, y revelando un misterio que abarca cuatro generaciones. La historia comienza en 2019, pero se extiende a través del viaje en el tiempo para incluir argumentos en 1986 y 1953, a medida que ciertos personajes de las familias principales de la serie se dan cuenta de la existencia de un agujero de gusano.');
insert into Serie values(nextval('serie_sequence'),'STRANGER THINGS','2016',3,'La historia arranca durante la década de los 80, en el pueblo ficticio de Hawkins, Indiana, cuando un niño llamado Will Byers desaparece misteriosamente, hecho que destapa los extraños sucesos que tienen lugar en la zona, producto de una serie de experimentos que realiza el gobierno en un laboratorio científico cercano. Además, en la ciudad aparecen fuerzas sobrenaturales inquietantes y una niña muy extraña. Ella, junto con los amigos de Will, se encargará de buscarlo, sin imaginar lo que tendrán que enfrentar para encontrarlo.');
insert into Serie values(nextval('serie_sequence'),'BLACK MIRROR','2011',5,'Black Mirror es una serie de televisión antológica británica de ciencia ficción distópica creada por Charlie Brooker y producida por Zeppotron para Endemol. Descrita por su productora como “un híbrido de The Twilight Zone y Relatos de lo inesperado que se nutre de nuestro malestar contemporáneo sobre nuestro mundo moderno” la serie se caracteriza por presentar relatos distópicos autoconclusivos que muestran generalmente un sentimiento de “tecno-paranoia” y analizan cómo la tecnología afecta al ser humano.');
insert into Serie values(nextval('serie_sequence'),'VIKINGOS','2013',6,'La serie está inspirada en los cuentos de los nórdicos de la alta edad media escandinava. En líneas generales, sigue las hazañas del legendario jefe vikingo Ragnar Lodbrok y su tripulación, familia y descendientes, tal como se estableció en las sagas del siglo XIII Ragnars saga loðbrókar y Ragnarssona þáttr, así como en la obra Gesta Danorum del siglo XII de Saxo Grammaticus. Las sagas legendarias nórdicas eran cuentos parcialmente ficticios basados en la tradición oral nórdica, escritas entre 200 y 400 años después de los eventos que describen.');
insert into Serie values(nextval('serie_sequence'),'SEX EDUCATION','2019',3,'La primera temporada sigue la historia de Otis Milburn, un adolescente socialmente incómodo, que es ambivalente sobre el sexo, debido a que su madre es una terapeuta. Después de ayudar inadvertidamente al acosador de la escuela con su ansiedad por el rendimiento sexual, Otis establece un negocio de asesoramiento sexual con Maeve, una compañera de clase.');
insert into Serie values(nextval('serie_sequence'),'LUPIN','2021',1,'La historia sigue al ladrón profesional Assane Diop, el único hijo de un inmigrante de Senegal que había llegado a Francia para buscar una vida mejor para su hijo. El padre de Assane es incriminado por el robo de un costoso collar de diamantes por parte de su empleador, el rico y poderoso Hubert Pellegrini, y se ahorca en su celda de la prisión por vergüenza, dejando al adolescente Assane huérfano. Veinticinco años después, inspirado por un libro sobre el caballero ladrón Arsène Lupin que su padre le había regalado en su cumpleaños, Assane se propone vengarse de la familia Pellegrini, usando su carisma y dominio del robo, subterfugio y disfraz para exponer los crímenes de Hubert.');
insert into Serie values(nextval('serie_sequence'),'GAMBITO DE DAMA','2020',1,'Gambito de dama es una historia ficticia que sigue la vida de una huérfana prodigio del ajedrez, Beth Harmon, durante su búsqueda para convertirse en la mejor jugadora de ajedrez del mundo mientras lucha con problemas emocionales y dependencia de las drogas y el alcohol. La historia comienza a mediados de la década de 1950 y continúa hasta la de 1960. La serie comienza en un orfanato de niñas donde Beth conoce a Jolene, una niña vibrante y amigable unos años mayor que ella; Helen Deardorff, la mujer que dirige el orfanato; y el Señor Shaibel, el conserje que enseña a Beth sus primeras lecciones de ajedrez, como era común durante la década de 1950.');
insert into Serie values(nextval('serie_sequence'),'SENSE 8','2015',2,'Sense 8 cuenta la historia de ocho desconocidos (Will, Riley, Capheus, Sun, Lito, Kala, Wolfgang y Nomi) de diferentes culturas, razas y orientaciones sexuales que, después de experimentar la trágica muerte de una mujer a través de visiones o sueños, se encuentran mental y emocionalmente conectados. A través de esta conexión, son capaces de comunicarse, sentirse y compartir sus conocimientos, idiomas y habilidades. Mientras intentan descubrir por qué están conectados y qué significa su conexión, reciben ayuda de un hombre misterioso llamado Jonas, el cual es otro sensate. Sin embargo, otro hombre llamado Whispers intenta capturarlos.');
insert into Serie values(nextval('serie_sequence'),'RIVERDALE','2017',4,'Al mismo tiempo que un nuevo año escolar da comienzo, la ciudad de Riverdale aún está reponiéndose de la trágica muerte reciente de Jason Blossom. Los acontecimientos que han tenido lugar durante el verano han hecho que Archie Andrews se dé cuenta de que quiere seguir una carrera musical. Asimismo, a Archie aún le pesa haber roto su amistad con Jughead Jones. Mientras tanto, Betty Cooper está ansiosa de ver a Archie, de quien está enamorada, sin embargo aún no está lista para revelarle sus verdaderos sentimientos. Cuando una nueva estudiante, Veronica Lodge, llega a Riverdale desde Nueva York junto a su madre, nace la chispa entre ella y Archie. Pero Veronica no quiere poner su nueva amistad con Betty en riesgo.');
insert into Serie values(nextval('serie_sequence'),'COBRA KAI','2018',3,'Cobra Kai es la secuela de la famosa saga cinematográfica Karate Kid. La serie sigue la historia 30 años después del campeonato de 1984, en el que Johnny no se encuentra en el mejor momento de su vida por lo que decide volver a abrir el famoso Dojo Cobra Kai para darle un giro. Es ahí cuando se reencuentra con Daniel, ahora convertido en un hombre de éxito, pero sin la ayuda de Miyagi, no logra encontrar el equilibrio en su vida. Después de perder su trabajo, Johnny usa el karate que aprendió en su día para defender a un vecino adolescente llamado Miguel Díaz, un chico asmático que vive con su madre soltera Carmen y su abuela Rosa. Éste, sorprendido por las destrezas de Johnny, pide que le enseñe kárate.');
insert into Serie values(nextval('serie_sequence'),'13 REASONS WHY','2017',4,'Un drama que golpea de lleno a la sociedad joven actual, en el que trata todos los conflictos a los que se enfrentan: bullying o machismo. Así como a las cuestiones sociales y de diversidad en cuanto al amor o la homosexualidad, tratados de una forma natural. Todas ellas se redondean con un tema casi tabú como el suicidio, principal protagonista con una fuerte dosis emocional en forma de cinta.');
insert into Serie values(nextval('serie_sequence'),'EL MUNDO OCULTO DE SABRINA','2018',4,'Es una adaptación de la mítica serie Sabrina, cosas de brujas. Esta vez sigue los orígenes de la bruja adolescente, en la que tiene que hacer frente a su doble naturaleza de bruja y mortal. Tiene por tanto que reconciliar así a sus dos partes desde lo más oscuro de la brujería, pues las fuerzas malignas amenzan a su familia, amigos e, incluso, a la humanidad.');
insert into Serie values(nextval('serie_sequence'),'HOW TO SELL DRUGS ONLINE (FAST)','2019',2,'Es una comedia alemana que sigue a un adolescente llamado Moritz, que estudia en el instituto, tiene 17 años y hará lo que sea para  recuperar al amor de su vida, la misma que ha vuelto de Estados Unidos a este recóndito pueblo alemán. Para conseguir este objetivo, se asocia con su mejor amigo Lenny y crean un negocio de drogas más grande de Europa en su propia habitación. Los amigos, vivirán intensas experiencias que distarán sus vidas de una normal adolescencia.');
insert into Serie values(nextval('serie_sequence'),'ELITE','2018',4,'Élite narra la vida de un grupo de estudiantes de un exclusivo colegio privado, al que llegan tres nuevos alumnos becados de clase humilde, provocando una confrontación entre ricos y pobres que desemboca en asesinatos y desapariciones de alumnos. La serie explora diversos conceptos asociados con los dramas adolescentes. La principal característica de la serie Élite es que por una parte se muestran clichés adolescentes, pero al mismo tiempo se presentan otros temas más progresivos que normalmente no son tratados en las ficciones sobre adolescentes: diversidad sexual, diferencias culturales, drogas, enfermedades, acoso, uso de redes sociales, corrupción, asesinatos, robos, etc.');
insert into Serie values(nextval('serie_sequence'),'LA CASA DE PAPEL','2017',4,'La Casa de Papel narra lo que se espera que sea el atraco perfecto al Museo de la Fábrica Nacional de Moneda y Timbre. La mente que idea este plan es El Profesor, un hombre que recluta a siete personas para llevar a cabo el gran golpe. Tokio es una joven atracadora muy buscada por la policía, Berlín asume el papel de "el cabecilla", Moscú es el experto en perforaciones, Río es "el informático", Nairobi es la falsificadora, Denver es el hijo de Moscú y, como siempre, falta la fuerza bruta: Helsinki y Oslo. La banda planea cada paso durante cinco meses, valoran todos los inconvenientes, todas las posibilidades.');
insert into Serie values(nextval('serie_sequence'),'DETRAS DE SUS OJOS','2021',1,'La historia se centra en Louise, una secretaria y madre soltera que tiene una vida muy rutinaria y desea tener más aventuras en su vida, por lo que una noche decide salir a un bar. Allí conoce a un hombre con el que se besa y siente que puede darle justo lo que necesita, pero descubrirá poco después que el misterioso hombre es David, que está casado y que es su nuevo jefe. Louise acaba forjando por accidente una amistad con Adele, la mujer de David, llevándola a cuestionarse sus acciones sumergida en un mar de mentiras y secretos.');
insert into Serie values(nextval('serie_sequence'),'ORANGE IS THE NEW BLACK','2013',7,'La serie sigue la vida de la recién comprometida Piper Chapman. La joven de Brooklyn se ve envuelta en un lío de drogas por el que termina siendo encarcelada, como consecuencia de la relación sentimental que mantuvo con Alex, una camello y su pareja en aquel momento. A pesar de ver como su vida y la relación con su prometido se van a pique, poco a poco se va adaptando a la vida de presidiaria llegando, incluso, a hacer amigas dentro de la cárcel.');
insert into Serie values(nextval('serie_sequence'),'THE END OF THE F***ING WORLD','2017',2,'The End of the F***ing World es una oscura comedia basada en en la novela gráfica de Charles S. Forsman (2013), que sigue a James, un psicópata que llama la atención a una chica rebelde llamada Alyssa. El chico tiene intenciones de matarla y aprovechan su instinto aventurero para embarcarse en un accidentado viaje de carretera que les cambiará la vida.');
insert into Serie values(nextval('serie_sequence'),'DAYBREAK','2019',1,'Daybreak es un drama ambientado en la ciudad post-apocalíptica de Gleendale (California). La serie narra la historia de un joven de 17 años, Josh, que busca a su novia desaparecida, Sam. Para esta búsqueda, se le une un antiguo abusón (Wesley), que ahora se ha convertido en un samurái pacifista, y una pirómana de 12 años (Angélica). Este peculiar grupo deben mantenerse a salvo en medio de bandas al estilo de Mad Max (deportistas malvados, animadoras convertidas en guerreras amazonas...), criaturas parecidas a zombis (Ghoulies) y todo lo que este mundo les ponga en el camino.');
insert into Serie values(nextval('serie_sequence'),'MALDITA','2020',1,'Es una serie que trata el relato de la Leyenda del Rey Arturo de manera re-versionada. De esta manera, conocemos a Nimue, una joven heroína con un misterioso don que es la encargada de conducir esta historia. A través de ella, vivimos y conocemos sus aventuras a lo largo de su camino en su propósito de convertirse en la poderosa y trágica Dama del Lago. Después de la dramática muerte de su madre, Nimue conoce a Arturo, y ve en él un compañero que poco esperaba. Un joven mercenario que trata de encontrar a Merlin para entregar una antigua espada. Durante su viaje, Nimue se convierte en toda una mujer llena de coraje y rebeldía que batalla contra los Paladines Rojos y el Rey Uther.');

